### ISSUE TITLE
Unpin jupyterlab=3.6.4

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/MED-condaenv#17]
Jupyterlab is pinned at `3.6.4` as there're issues with using `panel` widgets with `jupyterlab=4.0.0` and `4.0.1`. This pin should be removed once the compatibility issue is resolved.

At the time of writing this, latest relevant package versions on `conda-forge` were:

```
python=3.10.11
jupyterlab=4.0.1
hvplot=0.8.3
datashader=0.15.0
panel=1.1.0
```

## To replicate the issue

(courtesy of @headmetal)

```python
import panel as pn

def star_creator(number):
    #print('Updating number of stars to', number)
    return "⭐" * number

pn.extension()
slider = pn.widgets.IntSlider(value=5, start=1, end=10)
interactive_star_creator = pn.bind(star_creator, slider)
pn.Column(slider, interactive_star_creator)
```

Stars should update with the integer as the slider is moved.

**Comment by dougiesquire** [comment]
Just checked, and this issue is **not** resolved by updating to `jupyterlab=4.0.2`, which is now available on `conda-forge`

**Comment by dougiesquire** [comment]
@headmetal, do you know if your issue has been resolved by any recent updates? Can we unpin `jupyterlab`?

**Comment by headmetal** [comment]
I don't know if it has been resolved yet as I'm waiting for env fixes to test https://github.com/ACCESS-NRI/MED-live-diagnostics. Once that is going I'll look into it.

**Comment by dougiesquire** [comment]
The difficulty is that we may need to unpin this in order to fix the MED env... All good - I'll check in a different env

**Comment by headmetal** [comment]
Don't worry about it - do the fix so everything can work again, then I can test and go from there
