### ISSUE TITLE
add cdsapi to access-med?

### ISSUE THREAD

**Issue by svenbuder** [ACCESS-NRI/MED-condaenv#21]
This is a suggestion - maybe we do not need this if it is only us who download this data from CDS (https://cds.climate.copernicus.eu/) onto Gadi. I have installed a version in my home directory.

`cdsapi`client enables python-based automated download from Climate Data Storage.

For installation, see:
https://cds.climate.copernicus.eu/api-how-to#use-the-cds-api-client-for-data-access

**Comment by rbeucher** [comment]
I think we need to define what we want the conda med environment to be. I don't want it to be cluttered with too many things... Lets put this one on hold...
