### ISSUE TITLE
Missing packages for full UM file support in iris

### ISSUE THREAD

**Issue by dsroberts** [ACCESS-NRI/MED-condaenv#51]
Hi @rbeucher 

I'm trying to do some stress-testing of the xp65 conda environment in relation to https://github.com/coecms/cms-conda-singularity/issues/40 and it looks like there are a couple of missing optional `iris` dependencies that are needed to enable full UM file support. 
 * `mo_pack` - Required to read PP fields with packing enabled
 * `iris-grib` - Required to read GRIB format data

I'm not sure if there are more, `iris` doesn't seem to want to document its optional dependencies, but there are the ones I've found so far.

**Comment by rbeucher** [comment]
Hi @dsroberts 

Thanks for pointing that out. I'm gonna add them.

R

**Comment by dsroberts** [comment]
Can confirm this has gone through successfully and I can open packed PP files now.
